# This is for OS X
# Git prompt stuff from https://github.com/matijs/dotfiles/blob/dotfiles/.config/shell/prompt

# /Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh is used as provided

if [[ $OSTYPE =~ darwin ]]; then
  git_prompt=/Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh;
else
  git_prompt=/usr/share/git-core/contrib/completion/git-prompt.sh;
fi

if [[ -s ${git_prompt} ]]; then
  source "${git_prompt}";
  export GIT_PS1_SHOWDIRTYSTATE=true;
  export GIT_PS1_SHOWSTASHSTATE=true;
  export GIT_PS1_SHOWUPSTREAM='auto';
  export GIT_PS1_DESCRIBE_STYLE='branch';
  export GIT_PS1_SHOWCOLORHINTS=true;
fi

unset git_prompt;

# This zsh code from https://www.themoderncoder.com/add-git-branch-information-to-your-zsh-prompt/
# Load version control information
autoload -Uz vcs_info
precmd() { vcs_info }

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats 'on branch %b'

# Set up the prompt (with git branch name)
setopt PROMPT_SUBST
PROMPT='%n in ${PWD/#$HOME/~} ${vcs_info_msg_0_} > '
